### ISSUE TITLE
If clone answers from another assessment, need a means to mark it as copied

### ISSUE THREAD

**Issue by plschmitz** [CaRCC/rcd-nexus-portal#100]
This might or might not appear in the UI, but it will be useful for analysis of the data.

**Comment by plschmitz** [comment]
Perhaps we can just put this in the comments?  That would avoid a model change.

**Comment by plschmitz** [comment]
Use Comments on RCDProfile for this.

**Comment by plschmitz** [comment]
Moving to DV1 beta as this is not a core feature

**Comment by pphysch** [comment]
Implemented in 852b231
