### ISSUE TITLE
Need to implement data access policies for assessment contributors (submitters) and non-contributors/submitters

### ISSUE THREAD

**Issue by plschmitz** [CaRCC/rcd-nexus-portal#107]
Discussion in WG led to the following principles (Agreed by WG members): 
(To distinguish from the "contributor" role in editing an assessment, we will call the status for those who are at an institution that has submitted (and gotten an approval) for an assessment, "data_contributor"). The policies on this are:

- Everyone at an institution has **_ever_** a submitted and approved assessment ever gets access as a data_contributor for all of 2024. 
- After 2024, an institution must have a submitted and approved assessment within 3 years of the current date to have access as a data_contributor.
- For those who only do some sections (chart your own journey), they will have no data to see benchmarking comparisons on the topics they did not complete (this should be an incentive to complete as much as they can). We should make sure we highlight this in the UI to push them to complete more of the assessment. 
- We should notify folks who are within 6 months of losing data_contributor rights. 
   - We need a means of running some report for this (can be an admin UI function), and then we will send email by hand (i.e., this need not be automated in the system).

**Comment by plschmitz** [comment]
Is it dependent upon the user have a role on a given RCDProfile?  I.e., will "self.profiles" include any and all profiles for their institution? We want to ensure that anyone formally associated to an institution gets the rights for that institution. 
We also have to add the one-time tweak that says something like if len(self.rcd_profiles)>0 and (datetime.date.today().year == 2024).

**Comment by pphysch** [comment]
Implemented in 852b231
