### ISSUE TITLE
Profile create->import returns a 404

### ISSUE THREAD

**Issue by plschmitz** [CaRCC/rcd-nexus-portal#139]
Create a new profile and the UI offers the choice to import from a previous one (if one exists). Click on the button and no route is found (404 if not in debug).

**Comment by pphysch** [comment]
Just need to add a urls/rcd_profiles.py entry for the import view. Currently the create page is expecting it at the `/import` relative URL.

**Comment by plschmitz** [comment]
Moving to DV1 beta as this is not a core feature

**Comment by pphysch** [comment]
Fixed in 852b231
