### ISSUE TITLE
First time portal users should get nice set of popups that show how to use things

### ISSUE THREAD

**Issue by plschmitz** [CaRCC/rcd-nexus-portal#192]
Use a cookie to track that they have seen this (don't show again checkbox). 
Could either run in sequence, or on hover...
Need some ideas on this (Lauren???)
Possibilities: 
On landing screen, have a popup that explains the three kinds of visualizations they can explore ("Click on one of these to explore...")
On any of the viz main pages: 1) Main graph area shows visualization, and includes tools to download image, 2) filters allow you to narrow down which data you want to explore. Choose the type of visualization, slick on filters to filter on types of institutions, 3) View options to control size of viz (especially useful if you want to download a smaller image for use in a report). 
On the Caps Model data page, Explain what "coverage" is, Add something about the facings controls, benchmarking, explain the error bars and the view option to hide the error bars. Note that can click on legend elements to hide (e.g., can be useful if have multiple benchmarking years).

**Comment by lmichael107** [comment]
If having an embedded tutorial is too much development (per conversation with Patrick last Thursday, Aug 22), I would suggest a pop-up tutorial 'presentation' of no more than 6 slides you click through, or close without looking.

I agree that it would be good to cover the different major portions of the page, and to have a final slide that discusses the caveats of data interpretation, with link to further information as implemented to address #131.

In a later release, the presentation could also link out (new tab) to a future quick video that demonstrates the same content, instead.

**Comment by plschmitz** [comment]
Makes sense. As I work through the Quick start guide for the viewer, I will think about refactoring that material into a popup slideshow.

**Comment by plschmitz** [comment]
Moved some material on benchmarking to the Quick Start Guide, but need to do a quick start on the main charting and filtering UI.

**Comment by plschmitz** [comment]
Done on staging branch.
