### ISSUE TITLE
Rename and Re-Order "Chart View" and "Facing Detail" drop-downs in the Data Viewer

### ISSUE THREAD

**Issue by lmichael107** [CaRCC/rcd-nexus-portal#195]
When on this page: https://portal.rcd-nexus.org/dataviz/capsmodeldata

The drop-down headings under "Viewer" at top left are currently worded as "Chart View:" and "Facing Detail:".

Requests:

- [ ] Replace "Viewer" drop-down headings with "Compare By:" and "Assessment Data (by Facing):" to be more descriptive and intuitive. 
- [ ] Move the "Chart View:" drop-down to come after the current "Facing Detail" drop-down.
- [ ] Rename the top item for "Chart View:" from "Summary" to "Summary For All Institutions", to align with the top option for the current "Facing Detail:"

Some sources that use "compare" terminology:
https://www.atlassian.com/data/charts/bar-chart-complete-guide
https://journal.ahima.org/page/using-bar-charts-to-compare-data-in-categories
https://www.fusioncharts.com/blog/ways-to-do-bar-graph-comparison/
https://chartexpo.com/blog/types-of-comparison-charts

**Open to other inputs/votes on any of the above, via this issue thread!**

Example in this screenshot:
![Screenshot 2024-08-22 at 3 16 58 PM](https://github.com/user-attachments/assets/f08a9778-9ee1-45a6-b02c-f7169cb9119d)

**Comment by lmichael107** [comment]
Adding a note that this also means updates to the documentation and any images that exist elsewhere ...

**Comment by plschmitz** [comment]
Done on current branch
