### ISSUE TITLE
Report 'not enough data' for a missing category WITHIN a chart view

### ISSUE THREAD

**Issue by lmichael107** [CaRCC/rcd-nexus-portal#196]
Currently, a graph will be produced without data for one or more categories within the "Chart View". See the below examples.

I would be nice if the missing category were still shown at right, with some indicator (question mark or parenthetical) indicate "not enough data" or something like that.
![Screenshot 2024-08-26 at 2 48 02 PM](https://github.com/user-attachments/assets/bfc36c46-b278-4c19-b7e4-b61a85906b60)

**Comment by lmichael107** [comment]
Missed the following, before.
![Screenshot 2024-08-26 at 2 24 17 PM](https://github.com/user-attachments/assets/df62a59b-1193-4fb3-bfa8-e19ae847bbd9)

**Comment by plschmitz** [comment]
I am not sure that we can control this, but I will look into it. I think this is something that the graphing engine does by itself when there are **zero** institutions in a given category. This is not **us** filtering the data. 

This is one of those cases where someone could in theory use the tools to determine levels for a given institution with some careful filtering. We do not currently review the # of institutions in each category to remove categories within a filter where there are < 5 institutions.

**Comment by plschmitz** [comment]
Moving to 2.2 as this is fairly non-trivial. This happens deep inside logic we call, so we would have to do some extra checking to even detect this.

**Comment by plschmitz** [comment]
For now, just add a footnote about the issue

**Comment by plschmitz** [comment]
Added support in latest branch for do detect when categories are filtered (or otherwise unrepresented in dataset). Note that e.g., Reporting Structure currently lacks any data for the choice "Academic/Research Institute or Center" and so the note currently always appears for that compare-by choice. There is no clean way to work around that minor issue.
