### ISSUE TITLE
Find a way to add "Percent complete" to the Capabilities Assessment Admin listing

### ISSUE THREAD

**Issue by plschmitz** [CaRCC/rcd-nexus-portal#95]
In https://portal.rcd-nexus.org/admin/nexus/capabilitiesassessment/ really need to be able to see how far along they are (e.g., so we can reach out to them to offer help).

**Comment by plschmitz** [comment]
This is sort of working now, although we cannot sort or filter on it. For that, it needs to be a QuerySet method that creates an annotation to handle this.

**Comment by pphysch** [comment]
```python
class CapabilitiesAssessment(AssessmentBase):
    class QuerySet(models.QuerySet():
        ...

        def annotate_completed_percent(self):
            return self.annotate(completed_percent=... # figure out how to reimplement that in Django's ORM
```

Then override AssessmentAdmin.get_queryset() to use the above method, and the completed_percent can be referenced in the Admin model as if it were a normal model field.

**Comment by plschmitz** [comment]
We could add sort and filter on this but will defer that for now.

**Comment by plschmitz** [comment]
Turns out that since this is computed, sort and filter are hard (lots of custom coding that is not really justified). 
We can consider generating reports through the UI to address these kinds of things.
